### PR TITLE
ATTDEF rendering

### PR DESCRIPTION
**Pull request by kimkanghyune**
I made it to load the style item into the table to render the ATTDEF.
Get the appropriate hAlign,vAligh,widthFactor,fontSize and render it using textRenderer.

### CODE REVIEW

**Comment by vagran** [comment]
Cool! Do you have any sample files to test this feature?

**Comment by kimkanghyune** [comment]
I used [this](https://cadview-media.connectforyouserver.net/upload/48f34a98994011ed92a40ecc54b491ca/e7e6098cb5d811ed92a40ecc54b491ca/AEC.dxf)example.

**Comment by kimkanghyune** [comment]
I used [this](https://drive.google.com/file/d/1keX3u87Idbop3-ENwdDk4iFZ8TUBWp4a/view?usp=sharing) example.

**Comment by vagran** [comment]
As I understood meaning of this feature, `ATTDEF` entity is complementary to `ATTRIB` entity, both have strong relation to `BLOCK` and `INSERT`. Does this current state of the PR actually renders something useful on this example? I cannot find it visually, comparing with what is rendered by current `master`.

**Comment by kimkanghyune** [comment]
It currently does not render any meaningful data. It just renders meaningless values ​​in the right places. It needs to be further supplemented to render meaningful data.

**Pull request closed without merging**
